version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - javascript
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      production-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - docker
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github_actions
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
