// Generated by `node scripts/generate-contracts.mjs`. Do not edit by hand.
// Canonical source digest: sha256:5605117d761023dbc6a73d4c4cbe34e6376e7f9cde7aeb0d264be2f9a3ec1bbb

import {
  defineContractSchema,
  validateContract,
  type ContractSchema,
  type ValidationResult,
} from "./runtime";

export const contractVersion = "v1" as const;
export const contractSourceDigest =
  "sha256:5605117d761023dbc6a73d4c4cbe34e6376e7f9cde7aeb0d264be2f9a3ec1bbb" as const;

export interface ConnectorSyncResultV1 {
  readonly schemaVersion: 1;
  readonly requestId: string;
  readonly syncId: string;
  readonly outcome: "accepted" | "duplicate" | "quarantined";
  readonly acceptedEntries: number;
}

export const connectorSyncResultV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/connector-sync-result.schema.json",
  title: "ConnectorSyncResultV1",
  description:
    "Non-sensitive acknowledgement for a validated connector synchronization. Internal anomaly reasons are intentionally absent.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "requestId", "syncId", "outcome", "acceptedEntries"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    requestId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^req_[A-Za-z0-9_-]{22}$",
    },
    syncId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^syn_[A-Za-z0-9_-]{22}$",
    },
    outcome: {
      type: "string",
      enum: ["accepted", "duplicate", "quarantined"],
      minLength: 8,
      maxLength: 11,
    },
    acceptedEntries: {
      type: "integer",
      minimum: 0,
      maximum: 31,
    },
  },
} as const satisfies ContractSchema);

export function validateConnectorSyncResultV1(
  value: unknown,
): ValidationResult<ConnectorSyncResultV1> {
  return validateContract<ConnectorSyncResultV1>(connectorSyncResultV1Schema, value);
}

export interface ConnectorSyncV1 {
  readonly schemaVersion: 1;
  readonly sourceId: string;
  readonly syncId: string;
  readonly observedAt: string;
  readonly connectorVersion: string;
  readonly codexVersion: string;
  readonly dailyEntries: readonly { readonly codexReportedDate: string; readonly tokens: number }[];
}

export const connectorSyncV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/connector-sync.schema.json",
  title: "ConnectorSyncV1",
  description:
    "Bounded self-reported Community usage submitted by one source-bound device. Derived ranking and trust fields are server-owned and intentionally absent.",
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "sourceId",
    "syncId",
    "observedAt",
    "connectorVersion",
    "codexVersion",
    "dailyEntries",
  ],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    sourceId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^src_[A-Za-z0-9_-]{22}$",
    },
    syncId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^syn_[A-Za-z0-9_-]{22}$",
    },
    observedAt: {
      type: "string",
      minLength: 24,
      maxLength: 24,
      pattern: "^20[0-9]{2}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
      format: "date-time",
    },
    connectorVersion: {
      type: "string",
      minLength: 5,
      maxLength: 64,
      pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?$",
    },
    codexVersion: {
      type: "string",
      minLength: 5,
      maxLength: 64,
      pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?$",
    },
    dailyEntries: {
      type: "array",
      minItems: 1,
      maxItems: 31,
      "x-viberacing-uniqueBy": "codexReportedDate",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["codexReportedDate", "tokens"],
        properties: {
          codexReportedDate: {
            type: "string",
            minLength: 10,
            maxLength: 10,
            pattern: "^20[0-9]{2}-[0-9]{2}-[0-9]{2}$",
            format: "date",
          },
          tokens: {
            type: "integer",
            minimum: 0,
            maximum: 9007199254740991,
          },
        },
      },
    },
  },
} as const satisfies ContractSchema);

export function validateConnectorSyncV1(value: unknown): ValidationResult<ConnectorSyncV1> {
  return validateContract<ConnectorSyncV1>(connectorSyncV1Schema, value);
}

export interface ProblemDetailsV1 {
  readonly schemaVersion: 1;
  readonly requestId: string;
  readonly status: number;
  readonly errorCode:
    | "conflict"
    | "forbidden"
    | "internal_error"
    | "invalid_request"
    | "not_found"
    | "rate_limited"
    | "temporarily_unavailable"
    | "unauthorized"
    | "validation_failed";
  readonly title:
    | "Conflict"
    | "Forbidden"
    | "Internal server error"
    | "Invalid request"
    | "Not found"
    | "Rate limited"
    | "Temporarily unavailable"
    | "Unauthorized"
    | "Validation failed";
  readonly retryable: boolean;
}

export const problemDetailsV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/problem-details.schema.json",
  title: "ProblemDetailsV1",
  description:
    "Bounded public error response that carries a request ID and stable code without stack traces, SQL details, secrets, or internal hostnames.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "requestId", "status", "errorCode", "title", "retryable"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    requestId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^req_[A-Za-z0-9_-]{22}$",
    },
    status: {
      type: "integer",
      minimum: 400,
      maximum: 599,
    },
    errorCode: {
      type: "string",
      enum: [
        "conflict",
        "forbidden",
        "internal_error",
        "invalid_request",
        "not_found",
        "rate_limited",
        "temporarily_unavailable",
        "unauthorized",
        "validation_failed",
      ],
      minLength: 8,
      maxLength: 23,
    },
    title: {
      type: "string",
      enum: [
        "Conflict",
        "Forbidden",
        "Internal server error",
        "Invalid request",
        "Not found",
        "Rate limited",
        "Temporarily unavailable",
        "Unauthorized",
        "Validation failed",
      ],
      minLength: 1,
      maxLength: 23,
    },
    retryable: {
      type: "boolean",
    },
  },
} as const satisfies ContractSchema);

export function validateProblemDetailsV1(value: unknown): ValidationResult<ProblemDetailsV1> {
  return validateContract<ProblemDetailsV1>(problemDetailsV1Schema, value);
}
