// Generated by `node scripts/generate-contracts.mjs`. Do not edit by hand.
// Canonical source digest: sha256:31dbbc2e99a81978409c17344a447e2c70e989ad81a5a49918f990e5cf90a974

import {
  defineContractSchema,
  validateContract,
  type ContractSchema,
  type ValidationResult,
} from "./runtime";

export const contractVersion = "v1" as const;
export const contractSourceDigest =
  "sha256:31dbbc2e99a81978409c17344a447e2c70e989ad81a5a49918f990e5cf90a974" as const;

export interface CommunityScorePageV1 {
  readonly schemaVersion: 1;
  readonly trustTier: "community";
  readonly selfReported: true;
  readonly participants: readonly {
    readonly seasonStart: string;
    readonly seasonEnd: string;
    readonly scoreVersion: string;
    readonly seasonFinalized: boolean;
    readonly handle: string;
    readonly weeklyScore: number;
    readonly activeDays: number;
    readonly sourceCount: number;
    readonly rankPosition: number;
    readonly displayPosition: number;
  }[];
}

export const communityScorePageV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/community-score-page.schema.json",
  title: "CommunityScorePageV1",
  description:
    "Bounded response-only Community score page with explicit self-reported trust metadata and no private identifiers, raw usage, daily detail, or exact timestamps.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "trustTier", "selfReported", "participants"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    trustTier: {
      type: "string",
      const: "community",
      minLength: 9,
      maxLength: 9,
    },
    selfReported: {
      type: "boolean",
      const: true,
    },
    participants: {
      type: "array",
      minItems: 0,
      maxItems: 32,
      "x-viberacing-uniqueBy": "displayPosition",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "seasonStart",
          "seasonEnd",
          "scoreVersion",
          "seasonFinalized",
          "handle",
          "weeklyScore",
          "activeDays",
          "sourceCount",
          "rankPosition",
          "displayPosition",
        ],
        properties: {
          seasonStart: {
            type: "string",
            minLength: 10,
            maxLength: 10,
            pattern: "^(?:1999-12-27|20[0-9]{2}-[0-9]{2}-[0-9]{2})$",
            format: "date",
            "x-viberacing-dateMinimum": "1999-12-27",
            "x-viberacing-dateMaximum": "2099-12-28",
            "x-viberacing-isoWeekday": 1,
          },
          seasonEnd: {
            type: "string",
            minLength: 10,
            maxLength: 10,
            pattern: "^(?:20[0-9]{2}-[0-9]{2}-[0-9]{2}|2100-01-03)$",
            format: "date",
            "x-viberacing-dateMinimum": "2000-01-02",
            "x-viberacing-dateMaximum": "2100-01-03",
            "x-viberacing-isoWeekday": 7,
          },
          scoreVersion: {
            type: "string",
            minLength: 3,
            maxLength: 32,
            pattern: "^[a-z][a-z0-9_]{2,31}$",
          },
          seasonFinalized: {
            type: "boolean",
          },
          handle: {
            type: "string",
            minLength: 3,
            maxLength: 24,
            pattern: "^[a-z0-9][a-z0-9_-]{1,22}[a-z0-9]$",
          },
          weeklyScore: {
            type: "integer",
            minimum: 0,
            maximum: 7000,
          },
          activeDays: {
            type: "integer",
            minimum: 0,
            maximum: 7,
          },
          sourceCount: {
            type: "integer",
            minimum: 0,
            maximum: 32,
          },
          rankPosition: {
            type: "integer",
            minimum: 1,
            maximum: 32,
          },
          displayPosition: {
            type: "integer",
            minimum: 1,
            maximum: 32,
          },
        },
      },
    },
  },
} as const satisfies ContractSchema);

export function validateCommunityScorePageV1(
  value: unknown,
): ValidationResult<CommunityScorePageV1> {
  return validateContract<CommunityScorePageV1>(communityScorePageV1Schema, value);
}

export interface CommunityScoreQueryV1 {
  readonly seasonStart: string;
}

export const communityScoreQueryV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/community-score-query.schema.json",
  title: "CommunityScoreQueryV1",
  description:
    "Closed value contract for one bounded public Community score season. A future URL parser must reject duplicate parameters before applying this schema.",
  type: "object",
  additionalProperties: false,
  required: ["seasonStart"],
  properties: {
    seasonStart: {
      description: "Inclusive Monday season start from 1999-12-27 through 2099-12-28.",
      type: "string",
      minLength: 10,
      maxLength: 10,
      pattern: "^(?:1999-12-27|20[0-9]{2}-[0-9]{2}-[0-9]{2})$",
      format: "date",
      "x-viberacing-dateMinimum": "1999-12-27",
      "x-viberacing-dateMaximum": "2099-12-28",
      "x-viberacing-isoWeekday": 1,
    },
  },
} as const satisfies ContractSchema);

export function validateCommunityScoreQueryV1(
  value: unknown,
): ValidationResult<CommunityScoreQueryV1> {
  return validateContract<CommunityScoreQueryV1>(communityScoreQueryV1Schema, value);
}

export interface ConnectorSyncResultV1 {
  readonly schemaVersion: 1;
  readonly requestId: string;
  readonly syncId: string;
  readonly outcome: "accepted" | "duplicate" | "quarantined";
  readonly acceptedEntries: number;
}

export const connectorSyncResultV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/connector-sync-result.schema.json",
  title: "ConnectorSyncResultV1",
  description:
    "Non-sensitive acknowledgement for a validated connector synchronization. Internal anomaly reasons are intentionally absent.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "requestId", "syncId", "outcome", "acceptedEntries"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    requestId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^req_[A-Za-z0-9_-]{22}$",
    },
    syncId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^syn_[A-Za-z0-9_-]{22}$",
    },
    outcome: {
      type: "string",
      enum: ["accepted", "duplicate", "quarantined"],
      minLength: 8,
      maxLength: 11,
    },
    acceptedEntries: {
      type: "integer",
      minimum: 0,
      maximum: 31,
    },
  },
} as const satisfies ContractSchema);

export function validateConnectorSyncResultV1(
  value: unknown,
): ValidationResult<ConnectorSyncResultV1> {
  return validateContract<ConnectorSyncResultV1>(connectorSyncResultV1Schema, value);
}

export interface ConnectorSyncV1 {
  readonly schemaVersion: 1;
  readonly sourceId: string;
  readonly syncId: string;
  readonly observedAt: string;
  readonly connectorVersion: string;
  readonly codexVersion: string;
  readonly dailyEntries: readonly { readonly codexReportedDate: string; readonly tokens: number }[];
}

export const connectorSyncV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/connector-sync.schema.json",
  title: "ConnectorSyncV1",
  description:
    "Bounded self-reported Community usage submitted by one source-bound device. Derived ranking and trust fields are server-owned and intentionally absent.",
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "sourceId",
    "syncId",
    "observedAt",
    "connectorVersion",
    "codexVersion",
    "dailyEntries",
  ],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    sourceId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^src_[A-Za-z0-9_-]{22}$",
    },
    syncId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^syn_[A-Za-z0-9_-]{22}$",
    },
    observedAt: {
      type: "string",
      minLength: 24,
      maxLength: 24,
      pattern: "^20[0-9]{2}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
      format: "date-time",
    },
    connectorVersion: {
      type: "string",
      minLength: 5,
      maxLength: 64,
      pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?$",
    },
    codexVersion: {
      type: "string",
      minLength: 5,
      maxLength: 64,
      pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?$",
    },
    dailyEntries: {
      type: "array",
      minItems: 1,
      maxItems: 31,
      "x-viberacing-uniqueBy": "codexReportedDate",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["codexReportedDate", "tokens"],
        properties: {
          codexReportedDate: {
            type: "string",
            minLength: 10,
            maxLength: 10,
            pattern: "^20[0-9]{2}-[0-9]{2}-[0-9]{2}$",
            format: "date",
          },
          tokens: {
            type: "integer",
            minimum: 0,
            maximum: 9007199254740991,
          },
        },
      },
    },
  },
} as const satisfies ContractSchema);

export function validateConnectorSyncV1(value: unknown): ValidationResult<ConnectorSyncV1> {
  return validateContract<ConnectorSyncV1>(connectorSyncV1Schema, value);
}

export interface ProblemDetailsV1 {
  readonly schemaVersion: 1;
  readonly requestId: string;
  readonly status: number;
  readonly errorCode:
    | "conflict"
    | "forbidden"
    | "internal_error"
    | "invalid_request"
    | "method_not_allowed"
    | "not_acceptable"
    | "not_found"
    | "rate_limited"
    | "temporarily_unavailable"
    | "unauthorized"
    | "validation_failed";
  readonly title:
    | "Conflict"
    | "Forbidden"
    | "Internal server error"
    | "Invalid request"
    | "Method not allowed"
    | "Not acceptable"
    | "Not found"
    | "Rate limited"
    | "Temporarily unavailable"
    | "Unauthorized"
    | "Validation failed";
  readonly retryable: boolean;
}

export const problemDetailsV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/problem-details.schema.json",
  title: "ProblemDetailsV1",
  description:
    "Bounded public error response that carries a request ID and stable code without stack traces, SQL details, secrets, or internal hostnames.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "requestId", "status", "errorCode", "title", "retryable"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    requestId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^req_[A-Za-z0-9_-]{22}$",
    },
    status: {
      type: "integer",
      minimum: 400,
      maximum: 599,
    },
    errorCode: {
      type: "string",
      enum: [
        "conflict",
        "forbidden",
        "internal_error",
        "invalid_request",
        "method_not_allowed",
        "not_acceptable",
        "not_found",
        "rate_limited",
        "temporarily_unavailable",
        "unauthorized",
        "validation_failed",
      ],
      minLength: 8,
      maxLength: 23,
    },
    title: {
      type: "string",
      enum: [
        "Conflict",
        "Forbidden",
        "Internal server error",
        "Invalid request",
        "Method not allowed",
        "Not acceptable",
        "Not found",
        "Rate limited",
        "Temporarily unavailable",
        "Unauthorized",
        "Validation failed",
      ],
      minLength: 1,
      maxLength: 23,
    },
    retryable: {
      type: "boolean",
    },
  },
} as const satisfies ContractSchema);

export function validateProblemDetailsV1(value: unknown): ValidationResult<ProblemDetailsV1> {
  return validateContract<ProblemDetailsV1>(problemDetailsV1Schema, value);
}
