// Generated by `node scripts/generate-contracts.mjs`. Do not edit by hand.
// Canonical source digest: sha256:c4b3ee622c7284c8a5fa7aba73058732b53c29507b7b6dbd7312bc7a8fe56e34

import {
  defineContractSchema,
  validateContract,
  type ContractSchema,
  type ValidationResult,
} from "./runtime.js";

export const contractVersion = "v1" as const;
export const contractSourceDigest =
  "sha256:c4b3ee622c7284c8a5fa7aba73058732b53c29507b7b6dbd7312bc7a8fe56e34" as const;

export interface CarRecipeV1 {
  readonly schemaVersion: 1;
  readonly chassis: "formula" | "rally" | "roadster";
  readonly nose: "classic" | "scoop" | "wedge";
  readonly cockpit: "canopy" | "open" | "rally";
  readonly wing: "high" | "low" | "none";
  readonly wheels: "all-terrain" | "slick" | "street";
  readonly palette: "magenta" | "mint" | "redline" | "sunburst" | "turbo-blue";
  readonly trail: "grid" | "none" | "spark";
  readonly seed: number;
}

export const carRecipeV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/car-recipe.schema.json",
  title: "CarRecipeV1",
  description:
    "Closed project-owned pixel-car recipe. It contains no text, color, URL, path, file, markup, shader, executable instruction, or conversation content.",
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "chassis",
    "nose",
    "cockpit",
    "wing",
    "wheels",
    "palette",
    "trail",
    "seed",
  ],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    chassis: {
      type: "string",
      enum: ["formula", "rally", "roadster"],
      minLength: 5,
      maxLength: 8,
    },
    nose: {
      type: "string",
      enum: ["classic", "scoop", "wedge"],
      minLength: 5,
      maxLength: 7,
    },
    cockpit: {
      type: "string",
      enum: ["canopy", "open", "rally"],
      minLength: 4,
      maxLength: 6,
    },
    wing: {
      type: "string",
      enum: ["high", "low", "none"],
      minLength: 3,
      maxLength: 4,
    },
    wheels: {
      type: "string",
      enum: ["all-terrain", "slick", "street"],
      minLength: 5,
      maxLength: 11,
    },
    palette: {
      type: "string",
      enum: ["magenta", "mint", "redline", "sunburst", "turbo-blue"],
      minLength: 4,
      maxLength: 10,
    },
    trail: {
      type: "string",
      enum: ["grid", "none", "spark"],
      minLength: 4,
      maxLength: 5,
    },
    seed: {
      type: "integer",
      minimum: 0,
      maximum: 65535,
    },
  },
} as const satisfies ContractSchema);

export function validateCarRecipeV1(value: unknown): ValidationResult<CarRecipeV1> {
  return validateContract<CarRecipeV1>(carRecipeV1Schema, value);
}

export interface CommunityRacePageV1 {
  readonly schemaVersion: 1;
  readonly trustTier: "community";
  readonly selfReported: true;
  readonly participants: readonly {
    readonly seasonStart: string;
    readonly seasonEnd: string;
    readonly scoreVersion: string;
    readonly seasonFinalized: boolean;
    readonly handle: string;
    readonly carRecipe?: {
      readonly schemaVersion: 1;
      readonly chassis: "formula" | "rally" | "roadster";
      readonly nose: "classic" | "scoop" | "wedge";
      readonly cockpit: "canopy" | "open" | "rally";
      readonly wing: "high" | "low" | "none";
      readonly wheels: "all-terrain" | "slick" | "street";
      readonly palette: "magenta" | "mint" | "redline" | "sunburst" | "turbo-blue";
      readonly trail: "grid" | "none" | "spark";
      readonly seed: number;
    };
    readonly weeklyScore: number;
    readonly activeDays: number;
    readonly sourceCount: number;
    readonly rankPosition: number;
    readonly displayPosition: number;
  }[];
}

export const communityRacePageV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/community-race-page.schema.json",
  title: "CommunityRacePageV1",
  description:
    "Bounded response-only Community race page. It preserves the score contract fields and may add only the participant's current active enum-only CarRecipe, without private identifiers, proposal state, timestamps, raw usage, or daily detail.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "trustTier", "selfReported", "participants"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    trustTier: {
      type: "string",
      const: "community",
      minLength: 9,
      maxLength: 9,
    },
    selfReported: {
      type: "boolean",
      const: true,
    },
    participants: {
      type: "array",
      minItems: 0,
      maxItems: 32,
      "x-viberacing-uniqueBy": "displayPosition",
      items: {
        type: "object",
        additionalProperties: false,
        "x-viberacing-optionalProperties": ["carRecipe"],
        required: [
          "seasonStart",
          "seasonEnd",
          "scoreVersion",
          "seasonFinalized",
          "handle",
          "weeklyScore",
          "activeDays",
          "sourceCount",
          "rankPosition",
          "displayPosition",
        ],
        properties: {
          seasonStart: {
            type: "string",
            minLength: 10,
            maxLength: 10,
            pattern: "^(?:1999-12-27|20[0-9]{2}-[0-9]{2}-[0-9]{2})$",
            format: "date",
            "x-viberacing-dateMinimum": "1999-12-27",
            "x-viberacing-dateMaximum": "2099-12-28",
            "x-viberacing-isoWeekday": 1,
          },
          seasonEnd: {
            type: "string",
            minLength: 10,
            maxLength: 10,
            pattern: "^(?:20[0-9]{2}-[0-9]{2}-[0-9]{2}|2100-01-03)$",
            format: "date",
            "x-viberacing-dateMinimum": "2000-01-02",
            "x-viberacing-dateMaximum": "2100-01-03",
            "x-viberacing-isoWeekday": 7,
          },
          scoreVersion: {
            type: "string",
            minLength: 3,
            maxLength: 32,
            pattern: "^[a-z][a-z0-9_]{2,31}$",
          },
          seasonFinalized: {
            type: "boolean",
          },
          handle: {
            type: "string",
            minLength: 3,
            maxLength: 24,
            pattern: "^[a-z0-9][a-z0-9_-]{1,22}[a-z0-9]$",
          },
          carRecipe: {
            type: "object",
            additionalProperties: false,
            required: [
              "schemaVersion",
              "chassis",
              "nose",
              "cockpit",
              "wing",
              "wheels",
              "palette",
              "trail",
              "seed",
            ],
            properties: {
              schemaVersion: {
                type: "integer",
                const: 1,
                minimum: 1,
                maximum: 1,
              },
              chassis: {
                type: "string",
                enum: ["formula", "rally", "roadster"],
                minLength: 5,
                maxLength: 8,
              },
              nose: {
                type: "string",
                enum: ["classic", "scoop", "wedge"],
                minLength: 5,
                maxLength: 7,
              },
              cockpit: {
                type: "string",
                enum: ["canopy", "open", "rally"],
                minLength: 4,
                maxLength: 6,
              },
              wing: {
                type: "string",
                enum: ["high", "low", "none"],
                minLength: 3,
                maxLength: 4,
              },
              wheels: {
                type: "string",
                enum: ["all-terrain", "slick", "street"],
                minLength: 5,
                maxLength: 11,
              },
              palette: {
                type: "string",
                enum: ["magenta", "mint", "redline", "sunburst", "turbo-blue"],
                minLength: 4,
                maxLength: 10,
              },
              trail: {
                type: "string",
                enum: ["grid", "none", "spark"],
                minLength: 4,
                maxLength: 5,
              },
              seed: {
                type: "integer",
                minimum: 0,
                maximum: 65535,
              },
            },
          },
          weeklyScore: {
            type: "integer",
            minimum: 0,
            maximum: 7000,
          },
          activeDays: {
            type: "integer",
            minimum: 0,
            maximum: 7,
          },
          sourceCount: {
            type: "integer",
            minimum: 0,
            maximum: 32,
          },
          rankPosition: {
            type: "integer",
            minimum: 1,
            maximum: 32,
          },
          displayPosition: {
            type: "integer",
            minimum: 1,
            maximum: 32,
          },
        },
      },
    },
  },
} as const satisfies ContractSchema);

export function validateCommunityRacePageV1(value: unknown): ValidationResult<CommunityRacePageV1> {
  return validateContract<CommunityRacePageV1>(communityRacePageV1Schema, value);
}

export interface CommunityRaceStatusPageV1 {
  readonly schemaVersion: 1;
  readonly trustTier: "community";
  readonly selfReported: true;
  readonly participants: readonly {
    readonly seasonStart: string;
    readonly seasonEnd: string;
    readonly scoreVersion: string;
    readonly seasonFinalized: boolean;
    readonly handle: string;
    readonly carRecipe?: {
      readonly schemaVersion: 1;
      readonly chassis: "formula" | "rally" | "roadster";
      readonly nose: "classic" | "scoop" | "wedge";
      readonly cockpit: "canopy" | "open" | "rally";
      readonly wing: "high" | "low" | "none";
      readonly wheels: "all-terrain" | "slick" | "street";
      readonly palette: "magenta" | "mint" | "redline" | "sunburst" | "turbo-blue";
      readonly trail: "grid" | "none" | "spark";
      readonly seed: number;
    };
    readonly weeklyScore: number;
    readonly activeDays: number;
    readonly sourceCount: number;
    readonly rankPosition: number;
    readonly displayPosition: number;
    readonly freshnessDays: number;
    readonly streakDays?: number;
  }[];
}

export const communityRaceStatusPageV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/community-race-status-page.schema.json",
  title: "CommunityRaceStatusPageV1",
  description:
    "Bounded response-only Community race status page. It preserves the compatible race fields, adds only server-derived UTC-day-rounded freshness and an optional user-visible derived streak, and contains no private identifier, exact timestamp, raw usage, or daily detail.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "trustTier", "selfReported", "participants"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    trustTier: {
      type: "string",
      const: "community",
      minLength: 9,
      maxLength: 9,
    },
    selfReported: {
      type: "boolean",
      const: true,
    },
    participants: {
      type: "array",
      minItems: 0,
      maxItems: 32,
      "x-viberacing-uniqueBy": "displayPosition",
      items: {
        type: "object",
        additionalProperties: false,
        "x-viberacing-optionalProperties": ["carRecipe", "streakDays"],
        required: [
          "seasonStart",
          "seasonEnd",
          "scoreVersion",
          "seasonFinalized",
          "handle",
          "weeklyScore",
          "activeDays",
          "sourceCount",
          "rankPosition",
          "displayPosition",
          "freshnessDays",
        ],
        properties: {
          seasonStart: {
            type: "string",
            minLength: 10,
            maxLength: 10,
            pattern: "^(?:1999-12-27|20[0-9]{2}-[0-9]{2}-[0-9]{2})$",
            format: "date",
            "x-viberacing-dateMinimum": "1999-12-27",
            "x-viberacing-dateMaximum": "2099-12-28",
            "x-viberacing-isoWeekday": 1,
          },
          seasonEnd: {
            type: "string",
            minLength: 10,
            maxLength: 10,
            pattern: "^(?:20[0-9]{2}-[0-9]{2}-[0-9]{2}|2100-01-03)$",
            format: "date",
            "x-viberacing-dateMinimum": "2000-01-02",
            "x-viberacing-dateMaximum": "2100-01-03",
            "x-viberacing-isoWeekday": 7,
          },
          scoreVersion: {
            type: "string",
            minLength: 3,
            maxLength: 32,
            pattern: "^[a-z][a-z0-9_]{2,31}$",
          },
          seasonFinalized: {
            type: "boolean",
          },
          handle: {
            type: "string",
            minLength: 3,
            maxLength: 24,
            pattern: "^[a-z0-9][a-z0-9_-]{1,22}[a-z0-9]$",
          },
          carRecipe: {
            type: "object",
            additionalProperties: false,
            required: [
              "schemaVersion",
              "chassis",
              "nose",
              "cockpit",
              "wing",
              "wheels",
              "palette",
              "trail",
              "seed",
            ],
            properties: {
              schemaVersion: {
                type: "integer",
                const: 1,
                minimum: 1,
                maximum: 1,
              },
              chassis: {
                type: "string",
                enum: ["formula", "rally", "roadster"],
                minLength: 5,
                maxLength: 8,
              },
              nose: {
                type: "string",
                enum: ["classic", "scoop", "wedge"],
                minLength: 5,
                maxLength: 7,
              },
              cockpit: {
                type: "string",
                enum: ["canopy", "open", "rally"],
                minLength: 4,
                maxLength: 6,
              },
              wing: {
                type: "string",
                enum: ["high", "low", "none"],
                minLength: 3,
                maxLength: 4,
              },
              wheels: {
                type: "string",
                enum: ["all-terrain", "slick", "street"],
                minLength: 5,
                maxLength: 11,
              },
              palette: {
                type: "string",
                enum: ["magenta", "mint", "redline", "sunburst", "turbo-blue"],
                minLength: 4,
                maxLength: 10,
              },
              trail: {
                type: "string",
                enum: ["grid", "none", "spark"],
                minLength: 4,
                maxLength: 5,
              },
              seed: {
                type: "integer",
                minimum: 0,
                maximum: 65535,
              },
            },
          },
          weeklyScore: {
            type: "integer",
            minimum: 0,
            maximum: 7000,
          },
          activeDays: {
            type: "integer",
            minimum: 0,
            maximum: 7,
          },
          sourceCount: {
            type: "integer",
            minimum: 0,
            maximum: 32,
          },
          rankPosition: {
            type: "integer",
            minimum: 1,
            maximum: 32,
          },
          displayPosition: {
            type: "integer",
            minimum: 1,
            maximum: 32,
          },
          freshnessDays: {
            type: "integer",
            minimum: 0,
            maximum: 65535,
          },
          streakDays: {
            type: "integer",
            minimum: 0,
            maximum: 36533,
          },
        },
      },
    },
  },
} as const satisfies ContractSchema);

export function validateCommunityRaceStatusPageV1(
  value: unknown,
): ValidationResult<CommunityRaceStatusPageV1> {
  return validateContract<CommunityRaceStatusPageV1>(communityRaceStatusPageV1Schema, value);
}

export interface CommunityScorePageV1 {
  readonly schemaVersion: 1;
  readonly trustTier: "community";
  readonly selfReported: true;
  readonly participants: readonly {
    readonly seasonStart: string;
    readonly seasonEnd: string;
    readonly scoreVersion: string;
    readonly seasonFinalized: boolean;
    readonly handle: string;
    readonly weeklyScore: number;
    readonly activeDays: number;
    readonly sourceCount: number;
    readonly rankPosition: number;
    readonly displayPosition: number;
  }[];
}

export const communityScorePageV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/community-score-page.schema.json",
  title: "CommunityScorePageV1",
  description:
    "Bounded response-only Community score page with explicit self-reported trust metadata and no private identifiers, raw usage, daily detail, or exact timestamps.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "trustTier", "selfReported", "participants"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    trustTier: {
      type: "string",
      const: "community",
      minLength: 9,
      maxLength: 9,
    },
    selfReported: {
      type: "boolean",
      const: true,
    },
    participants: {
      type: "array",
      minItems: 0,
      maxItems: 32,
      "x-viberacing-uniqueBy": "displayPosition",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "seasonStart",
          "seasonEnd",
          "scoreVersion",
          "seasonFinalized",
          "handle",
          "weeklyScore",
          "activeDays",
          "sourceCount",
          "rankPosition",
          "displayPosition",
        ],
        properties: {
          seasonStart: {
            type: "string",
            minLength: 10,
            maxLength: 10,
            pattern: "^(?:1999-12-27|20[0-9]{2}-[0-9]{2}-[0-9]{2})$",
            format: "date",
            "x-viberacing-dateMinimum": "1999-12-27",
            "x-viberacing-dateMaximum": "2099-12-28",
            "x-viberacing-isoWeekday": 1,
          },
          seasonEnd: {
            type: "string",
            minLength: 10,
            maxLength: 10,
            pattern: "^(?:20[0-9]{2}-[0-9]{2}-[0-9]{2}|2100-01-03)$",
            format: "date",
            "x-viberacing-dateMinimum": "2000-01-02",
            "x-viberacing-dateMaximum": "2100-01-03",
            "x-viberacing-isoWeekday": 7,
          },
          scoreVersion: {
            type: "string",
            minLength: 3,
            maxLength: 32,
            pattern: "^[a-z][a-z0-9_]{2,31}$",
          },
          seasonFinalized: {
            type: "boolean",
          },
          handle: {
            type: "string",
            minLength: 3,
            maxLength: 24,
            pattern: "^[a-z0-9][a-z0-9_-]{1,22}[a-z0-9]$",
          },
          weeklyScore: {
            type: "integer",
            minimum: 0,
            maximum: 7000,
          },
          activeDays: {
            type: "integer",
            minimum: 0,
            maximum: 7,
          },
          sourceCount: {
            type: "integer",
            minimum: 0,
            maximum: 32,
          },
          rankPosition: {
            type: "integer",
            minimum: 1,
            maximum: 32,
          },
          displayPosition: {
            type: "integer",
            minimum: 1,
            maximum: 32,
          },
        },
      },
    },
  },
} as const satisfies ContractSchema);

export function validateCommunityScorePageV1(
  value: unknown,
): ValidationResult<CommunityScorePageV1> {
  return validateContract<CommunityScorePageV1>(communityScorePageV1Schema, value);
}

export interface CommunityScoreQueryV1 {
  readonly seasonStart: string;
}

export const communityScoreQueryV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/community-score-query.schema.json",
  title: "CommunityScoreQueryV1",
  description:
    "Closed value contract for one bounded public Community score season. A future URL parser must reject duplicate parameters before applying this schema.",
  type: "object",
  additionalProperties: false,
  required: ["seasonStart"],
  properties: {
    seasonStart: {
      description: "Inclusive Monday season start from 1999-12-27 through 2099-12-28.",
      type: "string",
      minLength: 10,
      maxLength: 10,
      pattern: "^(?:1999-12-27|20[0-9]{2}-[0-9]{2}-[0-9]{2})$",
      format: "date",
      "x-viberacing-dateMinimum": "1999-12-27",
      "x-viberacing-dateMaximum": "2099-12-28",
      "x-viberacing-isoWeekday": 1,
    },
  },
} as const satisfies ContractSchema);

export function validateCommunityScoreQueryV1(
  value: unknown,
): ValidationResult<CommunityScoreQueryV1> {
  return validateContract<CommunityScoreQueryV1>(communityScoreQueryV1Schema, value);
}

export interface CommunityTokenRaceStatusPageV1 {
  readonly schemaVersion: 1;
  readonly trustTier: "community";
  readonly selfReported: true;
  readonly participants: readonly {
    readonly seasonStart: string;
    readonly seasonEnd: string;
    readonly metricVersion: "community_tokens_v1";
    readonly seasonFinalized: boolean;
    readonly handle: string;
    readonly carRecipe?: {
      readonly schemaVersion: 1;
      readonly chassis: "formula" | "rally" | "roadster";
      readonly nose: "classic" | "scoop" | "wedge";
      readonly cockpit: "canopy" | "open" | "rally";
      readonly wing: "high" | "low" | "none";
      readonly wheels: "all-terrain" | "slick" | "street";
      readonly palette: "magenta" | "mint" | "redline" | "sunburst" | "turbo-blue";
      readonly trail: "grid" | "none" | "spark";
      readonly seed: number;
    };
    readonly weeklyTokenTotal: number;
    readonly activeDays: number;
    readonly sourceCount: number;
    readonly rankPosition: number;
    readonly displayPosition: number;
    readonly freshnessDays: number;
    readonly streakDays?: number;
  }[];
}

export const communityTokenRaceStatusPageV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/community-token-race-status-page.schema.json",
  title: "CommunityTokenRaceStatusPageV1",
  description:
    "Bounded response-only Community leaderboard of exact self-reported weekly token totals. It includes only current public presentation metadata and contains no private identifier, exact timestamp, raw request, source detail, or daily token history.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "trustTier", "selfReported", "participants"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    trustTier: {
      type: "string",
      const: "community",
      minLength: 9,
      maxLength: 9,
    },
    selfReported: {
      type: "boolean",
      const: true,
    },
    participants: {
      type: "array",
      minItems: 0,
      maxItems: 32,
      "x-viberacing-uniqueBy": "displayPosition",
      items: {
        type: "object",
        additionalProperties: false,
        "x-viberacing-optionalProperties": ["carRecipe", "streakDays"],
        required: [
          "seasonStart",
          "seasonEnd",
          "metricVersion",
          "seasonFinalized",
          "handle",
          "weeklyTokenTotal",
          "activeDays",
          "sourceCount",
          "rankPosition",
          "displayPosition",
          "freshnessDays",
        ],
        properties: {
          seasonStart: {
            type: "string",
            minLength: 10,
            maxLength: 10,
            pattern: "^(?:1999-12-27|20[0-9]{2}-[0-9]{2}-[0-9]{2})$",
            format: "date",
            "x-viberacing-dateMinimum": "1999-12-27",
            "x-viberacing-dateMaximum": "2099-12-28",
            "x-viberacing-isoWeekday": 1,
          },
          seasonEnd: {
            type: "string",
            minLength: 10,
            maxLength: 10,
            pattern: "^(?:20[0-9]{2}-[0-9]{2}-[0-9]{2}|2100-01-03)$",
            format: "date",
            "x-viberacing-dateMinimum": "2000-01-02",
            "x-viberacing-dateMaximum": "2100-01-03",
            "x-viberacing-isoWeekday": 7,
          },
          metricVersion: {
            type: "string",
            const: "community_tokens_v1",
            minLength: 19,
            maxLength: 19,
          },
          seasonFinalized: {
            type: "boolean",
          },
          handle: {
            type: "string",
            minLength: 3,
            maxLength: 24,
            pattern: "^[a-z0-9][a-z0-9_-]{1,22}[a-z0-9]$",
          },
          carRecipe: {
            type: "object",
            additionalProperties: false,
            required: [
              "schemaVersion",
              "chassis",
              "nose",
              "cockpit",
              "wing",
              "wheels",
              "palette",
              "trail",
              "seed",
            ],
            properties: {
              schemaVersion: {
                type: "integer",
                const: 1,
                minimum: 1,
                maximum: 1,
              },
              chassis: {
                type: "string",
                enum: ["formula", "rally", "roadster"],
                minLength: 5,
                maxLength: 8,
              },
              nose: {
                type: "string",
                enum: ["classic", "scoop", "wedge"],
                minLength: 5,
                maxLength: 7,
              },
              cockpit: {
                type: "string",
                enum: ["canopy", "open", "rally"],
                minLength: 4,
                maxLength: 6,
              },
              wing: {
                type: "string",
                enum: ["high", "low", "none"],
                minLength: 3,
                maxLength: 4,
              },
              wheels: {
                type: "string",
                enum: ["all-terrain", "slick", "street"],
                minLength: 5,
                maxLength: 11,
              },
              palette: {
                type: "string",
                enum: ["magenta", "mint", "redline", "sunburst", "turbo-blue"],
                minLength: 4,
                maxLength: 10,
              },
              trail: {
                type: "string",
                enum: ["grid", "none", "spark"],
                minLength: 4,
                maxLength: 5,
              },
              seed: {
                type: "integer",
                minimum: 0,
                maximum: 65535,
              },
            },
          },
          weeklyTokenTotal: {
            type: "integer",
            minimum: 0,
            maximum: 9007199254740991,
          },
          activeDays: {
            type: "integer",
            minimum: 0,
            maximum: 7,
          },
          sourceCount: {
            type: "integer",
            minimum: 0,
            maximum: 32,
          },
          rankPosition: {
            type: "integer",
            minimum: 1,
            maximum: 32,
          },
          displayPosition: {
            type: "integer",
            minimum: 1,
            maximum: 32,
          },
          freshnessDays: {
            type: "integer",
            minimum: 0,
            maximum: 65535,
          },
          streakDays: {
            type: "integer",
            minimum: 0,
            maximum: 36533,
          },
        },
      },
    },
  },
} as const satisfies ContractSchema);

export function validateCommunityTokenRaceStatusPageV1(
  value: unknown,
): ValidationResult<CommunityTokenRaceStatusPageV1> {
  return validateContract<CommunityTokenRaceStatusPageV1>(
    communityTokenRaceStatusPageV1Schema,
    value,
  );
}

export interface ConnectorCarProposalResultV1 {
  readonly schemaVersion: 1;
  readonly requestId: string;
  readonly outcome: "accepted";
}

export const connectorCarProposalResultV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/connector-car-proposal-result.schema.json",
  title: "ConnectorCarProposalResultV1",
  description:
    "Generic acknowledgement that one authenticated device proposal was stored for explicit browser review. It exposes no proposal or profile identifier.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "requestId", "outcome"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    requestId: {
      type: "string",
      pattern: "^req_[A-Za-z0-9_-]{22}$",
      minLength: 26,
      maxLength: 26,
    },
    outcome: {
      type: "string",
      const: "accepted",
      minLength: 8,
      maxLength: 8,
    },
  },
} as const satisfies ContractSchema);

export function validateConnectorCarProposalResultV1(
  value: unknown,
): ValidationResult<ConnectorCarProposalResultV1> {
  return validateContract<ConnectorCarProposalResultV1>(connectorCarProposalResultV1Schema, value);
}

export interface ConnectorPairingPollResultV1 {
  readonly schemaVersion: 1;
  readonly requestId: string;
  readonly deviceBindings: readonly { readonly sourceId: string; readonly deviceId: string }[];
}

export const connectorPairingPollResultV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/connector-pairing-poll-result.schema.json",
  title: "ConnectorPairingPollResultV1",
  description:
    "Generic pending response or the single activated source/device binding available to the polling connector.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "requestId", "deviceBindings"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    requestId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^req_[A-Za-z0-9_-]{22}$",
    },
    deviceBindings: {
      type: "array",
      minItems: 0,
      maxItems: 1,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["sourceId", "deviceId"],
        properties: {
          sourceId: {
            type: "string",
            minLength: 26,
            maxLength: 26,
            pattern: "^src_[A-Za-z0-9_-]{22}$",
          },
          deviceId: {
            type: "string",
            minLength: 26,
            maxLength: 26,
            pattern: "^dev_[A-Za-z0-9_-]{22}$",
          },
        },
      },
    },
  },
} as const satisfies ContractSchema);

export function validateConnectorPairingPollResultV1(
  value: unknown,
): ValidationResult<ConnectorPairingPollResultV1> {
  return validateContract<ConnectorPairingPollResultV1>(connectorPairingPollResultV1Schema, value);
}

export interface ConnectorPairingPollV1 {
  readonly schemaVersion: 1;
  readonly pollToken: string;
  readonly possessionSignature: string;
}

export const connectorPairingPollV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/connector-pairing-poll.schema.json",
  title: "ConnectorPairingPollV1",
  description:
    "Closed polling request that presents one short-lived token and the exact pending-key possession signature.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "pollToken", "possessionSignature"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    pollToken: {
      type: "string",
      minLength: 43,
      maxLength: 43,
      pattern: "^[A-Za-z0-9_-]{43}$",
    },
    possessionSignature: {
      type: "string",
      minLength: 86,
      maxLength: 86,
      pattern: "^[A-Za-z0-9_-]{86}$",
    },
  },
} as const satisfies ContractSchema);

export function validateConnectorPairingPollV1(
  value: unknown,
): ValidationResult<ConnectorPairingPollV1> {
  return validateContract<ConnectorPairingPollV1>(connectorPairingPollV1Schema, value);
}

export interface ConnectorPairingStartResultV1 {
  readonly schemaVersion: 1;
  readonly requestId: string;
  readonly pairingId: string;
  readonly pollToken: string;
  readonly pairingChallengeBase64Url: string;
  readonly userCode: string;
  readonly expiresAt: string;
}

export const connectorPairingStartResultV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/connector-pairing-start-result.schema.json",
  title: "ConnectorPairingStartResultV1",
  description:
    "One-time short-lived pairing material returned only after a pending transaction is committed.",
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "requestId",
    "pairingId",
    "pollToken",
    "pairingChallengeBase64Url",
    "userCode",
    "expiresAt",
  ],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    requestId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^req_[A-Za-z0-9_-]{22}$",
    },
    pairingId: {
      type: "string",
      minLength: 36,
      maxLength: 36,
      pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    },
    pollToken: {
      type: "string",
      minLength: 43,
      maxLength: 43,
      pattern: "^[A-Za-z0-9_-]{43}$",
    },
    pairingChallengeBase64Url: {
      type: "string",
      minLength: 43,
      maxLength: 43,
      pattern: "^[A-Za-z0-9_-]{43}$",
    },
    userCode: {
      type: "string",
      minLength: 14,
      maxLength: 14,
      pattern: "^[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}$",
    },
    expiresAt: {
      type: "string",
      format: "date-time",
      minLength: 24,
      maxLength: 24,
      pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
    },
  },
} as const satisfies ContractSchema);

export function validateConnectorPairingStartResultV1(
  value: unknown,
): ValidationResult<ConnectorPairingStartResultV1> {
  return validateContract<ConnectorPairingStartResultV1>(
    connectorPairingStartResultV1Schema,
    value,
  );
}

export interface ConnectorPairingStartV1 {
  readonly schemaVersion: 1;
  readonly devicePublicKeyBase64Url: string;
  readonly deviceLabel: string;
  readonly connectorVersion: string;
  readonly osFamily: "linux" | "macos" | "windows";
  readonly architecture: "aarch64" | "x86_64";
}

export const connectorPairingStartV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/connector-pairing-start.schema.json",
  title: "ConnectorPairingStartV1",
  description:
    "Closed anonymous request that starts one short-lived connector pairing transaction without account, usage, or credential data.",
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "devicePublicKeyBase64Url",
    "deviceLabel",
    "connectorVersion",
    "osFamily",
    "architecture",
  ],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    devicePublicKeyBase64Url: {
      type: "string",
      minLength: 43,
      maxLength: 43,
      pattern: "^[A-Za-z0-9_-]{43}$",
    },
    deviceLabel: {
      type: "string",
      minLength: 1,
      maxLength: 64,
      pattern: "^[^\\u0000-\\u001F\\u007F-\\u009F]+$",
    },
    connectorVersion: {
      type: "string",
      minLength: 5,
      maxLength: 64,
      pattern:
        "^(?:0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)(?:-(?:(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:\\.(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\\+(?:[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?$",
    },
    osFamily: {
      type: "string",
      enum: ["linux", "macos", "windows"],
      minLength: 5,
      maxLength: 7,
    },
    architecture: {
      type: "string",
      enum: ["aarch64", "x86_64"],
      minLength: 6,
      maxLength: 7,
    },
  },
} as const satisfies ContractSchema);

export function validateConnectorPairingStartV1(
  value: unknown,
): ValidationResult<ConnectorPairingStartV1> {
  return validateContract<ConnectorPairingStartV1>(connectorPairingStartV1Schema, value);
}

export interface ProblemDetailsV1 {
  readonly schemaVersion: 1;
  readonly requestId: string;
  readonly status: number;
  readonly errorCode:
    | "conflict"
    | "forbidden"
    | "internal_error"
    | "invalid_request"
    | "method_not_allowed"
    | "not_acceptable"
    | "not_found"
    | "rate_limited"
    | "temporarily_unavailable"
    | "unauthorized"
    | "validation_failed";
  readonly title:
    | "Conflict"
    | "Forbidden"
    | "Internal server error"
    | "Invalid request"
    | "Method not allowed"
    | "Not acceptable"
    | "Not found"
    | "Rate limited"
    | "Temporarily unavailable"
    | "Unauthorized"
    | "Validation failed";
  readonly retryable: boolean;
}

export const problemDetailsV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/problem-details.schema.json",
  title: "ProblemDetailsV1",
  description:
    "Bounded public error response that carries a request ID and stable code without stack traces, SQL details, secrets, or internal hostnames.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "requestId", "status", "errorCode", "title", "retryable"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    requestId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^req_[A-Za-z0-9_-]{22}$",
    },
    status: {
      type: "integer",
      minimum: 400,
      maximum: 599,
    },
    errorCode: {
      type: "string",
      enum: [
        "conflict",
        "forbidden",
        "internal_error",
        "invalid_request",
        "method_not_allowed",
        "not_acceptable",
        "not_found",
        "rate_limited",
        "temporarily_unavailable",
        "unauthorized",
        "validation_failed",
      ],
      minLength: 8,
      maxLength: 23,
    },
    title: {
      type: "string",
      enum: [
        "Conflict",
        "Forbidden",
        "Internal server error",
        "Invalid request",
        "Method not allowed",
        "Not acceptable",
        "Not found",
        "Rate limited",
        "Temporarily unavailable",
        "Unauthorized",
        "Validation failed",
      ],
      minLength: 1,
      maxLength: 23,
    },
    retryable: {
      type: "boolean",
    },
  },
} as const satisfies ContractSchema);

export function validateProblemDetailsV1(value: unknown): ValidationResult<ProblemDetailsV1> {
  return validateContract<ProblemDetailsV1>(problemDetailsV1Schema, value);
}

export interface UsageSyncResultV1 {
  readonly schemaVersion: 1;
  readonly requestId: string;
  readonly syncId: string;
  readonly outcome: "accepted" | "duplicate" | "quarantined";
  readonly acceptedEntries: number;
}

export const usageSyncResultV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/usage-sync-result.schema.json",
  title: "UsageSyncResultV1",
  description:
    "Non-sensitive acknowledgement for one validated provider-neutral usage synchronization. Derived provider and internal anomaly reasons are intentionally absent.",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "requestId", "syncId", "outcome", "acceptedEntries"],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    requestId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^req_[A-Za-z0-9_-]{22}$",
    },
    syncId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^syn_[A-Za-z0-9_-]{22}$",
    },
    outcome: {
      type: "string",
      enum: ["accepted", "duplicate", "quarantined"],
      minLength: 8,
      maxLength: 11,
    },
    acceptedEntries: {
      type: "integer",
      minimum: 0,
      maximum: 31,
    },
  },
} as const satisfies ContractSchema);

export function validateUsageSyncResultV1(value: unknown): ValidationResult<UsageSyncResultV1> {
  return validateContract<UsageSyncResultV1>(usageSyncResultV1Schema, value);
}

export interface UsageSyncV1 {
  readonly schemaVersion: 1;
  readonly sourceId: string;
  readonly syncId: string;
  readonly observedAt: string;
  readonly clientVersion: string;
  readonly agentVersion: string;
  readonly dailyEntries: readonly {
    readonly reportedDate: string;
    readonly dailyTokenTotal: number;
  }[];
}

export const usageSyncV1Schema = defineContractSchema({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://schemas.viberacing.example/v1/usage-sync.schema.json",
  title: "UsageSyncV1",
  description:
    "Bounded provider-neutral Community usage submitted by one source-bound device. Provider attribution, accounting revision, ranking, and trust fields are server-owned and intentionally absent.",
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "sourceId",
    "syncId",
    "observedAt",
    "clientVersion",
    "agentVersion",
    "dailyEntries",
  ],
  properties: {
    schemaVersion: {
      type: "integer",
      const: 1,
      minimum: 1,
      maximum: 1,
    },
    sourceId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^src_[A-Za-z0-9_-]{22}$",
    },
    syncId: {
      type: "string",
      minLength: 26,
      maxLength: 26,
      pattern: "^syn_[A-Za-z0-9_-]{22}$",
    },
    observedAt: {
      type: "string",
      minLength: 24,
      maxLength: 24,
      pattern: "^20[0-9]{2}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
      format: "date-time",
    },
    clientVersion: {
      type: "string",
      minLength: 5,
      maxLength: 64,
      pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?$",
    },
    agentVersion: {
      type: "string",
      minLength: 5,
      maxLength: 64,
      pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?$",
    },
    dailyEntries: {
      type: "array",
      minItems: 1,
      maxItems: 31,
      "x-viberacing-uniqueBy": "reportedDate",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["reportedDate", "dailyTokenTotal"],
        properties: {
          reportedDate: {
            type: "string",
            minLength: 10,
            maxLength: 10,
            pattern: "^20[0-9]{2}-[0-9]{2}-[0-9]{2}$",
            format: "date",
          },
          dailyTokenTotal: {
            type: "integer",
            minimum: 0,
            maximum: 9007199254740991,
          },
        },
      },
    },
  },
} as const satisfies ContractSchema);

export function validateUsageSyncV1(value: unknown): ValidationResult<UsageSyncV1> {
  return validateContract<UsageSyncV1>(usageSyncV1Schema, value);
}
